version: '3.8'

services:
  trainer-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./trainer.db:/app/trainer.db
    environment:
      - SQLITE_DB_PATH=/app/trainer.db
    restart: always

  # SQLite does not require a separate service, as it is file-based.
  # The database file is mounted as a volume in the trainer-app service.